[package]
name = "restaurant_modules"
version = "0.1.0"
authors = ["Ari Marin <ari.marin@oscar.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
